language: clojure
lein: 2.8.1

script: lein do cljfmt check, eastwood, test

deploy:
  # Deploy binaries to Clojars
  - provider: script
    skip_cleanup: true
    script: lein deploy
    on:
      tags: true
cache:
  directories:
    - $HOME/.m2
